export type PhoneCountry = {
  iso: string;
  name: string;
  dialCode: string;
  flag: string;
  nationalMax: number;
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso: 'BR', name: 'Brasil', dialCode: '55', flag: '🇧🇷', nationalMax: 11 },
  { iso: 'AF', name: 'Afeganistão', dialCode: '93', flag: '🇦🇫', nationalMax: 9 },
  { iso: 'ZA', name: 'África do Sul', dialCode: '27', flag: '🇿🇦', nationalMax: 9 },
  { iso: 'AL', name: 'Albânia', dialCode: '355', flag: '🇦🇱', nationalMax: 9 },
  { iso: 'DE', name: 'Alemanha', dialCode: '49', flag: '🇩🇪', nationalMax: 11 },
  { iso: 'AD', name: 'Andorra', dialCode: '376', flag: '🇦🇩', nationalMax: 6 },
  { iso: 'AO', name: 'Angola', dialCode: '244', flag: '🇦🇴', nationalMax: 9 },
  { iso: 'SA', name: 'Arábia Saudita', dialCode: '966', flag: '🇸🇦', nationalMax: 9 },
  { iso: 'DZ', name: 'Argélia', dialCode: '213', flag: '🇩🇿', nationalMax: 9 },
  { iso: 'AR', name: 'Argentina', dialCode: '54', flag: '🇦🇷', nationalMax: 10 },
  { iso: 'AM', name: 'Armênia', dialCode: '374', flag: '🇦🇲', nationalMax: 8 },
  { iso: 'AU', name: 'Austrália', dialCode: '61', flag: '🇦🇺', nationalMax: 9 },
  { iso: 'AT', name: 'Áustria', dialCode: '43', flag: '🇦🇹', nationalMax: 10 },
  { iso: 'AZ', name: 'Azerbaijão', dialCode: '994', flag: '🇦🇿', nationalMax: 9 },
  { iso: 'BD', name: 'Bangladesh', dialCode: '880', flag: '🇧🇩', nationalMax: 10 },
  { iso: 'BE', name: 'Bélgica', dialCode: '32', flag: '🇧🇪', nationalMax: 9 },
  { iso: 'BO', name: 'Bolívia', dialCode: '591', flag: '🇧🇴', nationalMax: 8 },
  { iso: 'BA', name: 'Bósnia e Herzegovina', dialCode: '387', flag: '🇧🇦', nationalMax: 8 },
  { iso: 'BW', name: 'Botsuana', dialCode: '267', flag: '🇧🇼', nationalMax: 8 },
  { iso: 'BG', name: 'Bulgária', dialCode: '359', flag: '🇧🇬', nationalMax: 9 },
  { iso: 'CV', name: 'Cabo Verde', dialCode: '238', flag: '🇨🇻', nationalMax: 7 },
  { iso: 'CM', name: 'Camarões', dialCode: '237', flag: '🇨🇲', nationalMax: 9 },
  { iso: 'KH', name: 'Camboja', dialCode: '855', flag: '🇰🇭', nationalMax: 9 },
  { iso: 'CA', name: 'Canadá', dialCode: '1', flag: '🇨🇦', nationalMax: 10 },
  { iso: 'QA', name: 'Catar', dialCode: '974', flag: '🇶🇦', nationalMax: 8 },
  { iso: 'KZ', name: 'Cazaquistão', dialCode: '7', flag: '🇰🇿', nationalMax: 10 },
  { iso: 'CL', name: 'Chile', dialCode: '56', flag: '🇨🇱', nationalMax: 9 },
  { iso: 'CN', name: 'China', dialCode: '86', flag: '🇨🇳', nationalMax: 11 },
  { iso: 'CY', name: 'Chipre', dialCode: '357', flag: '🇨🇾', nationalMax: 8 },
  { iso: 'CO', name: 'Colômbia', dialCode: '57', flag: '🇨🇴', nationalMax: 10 },
  { iso: 'KR', name: 'Coreia do Sul', dialCode: '82', flag: '🇰🇷', nationalMax: 10 },
  { iso: 'CI', name: 'Costa do Marfim', dialCode: '225', flag: '🇨🇮', nationalMax: 10 },
  { iso: 'CR', name: 'Costa Rica', dialCode: '506', flag: '🇨🇷', nationalMax: 8 },
  { iso: 'HR', name: 'Croácia', dialCode: '385', flag: '🇭🇷', nationalMax: 9 },
  { iso: 'CU', name: 'Cuba', dialCode: '53', flag: '🇨🇺', nationalMax: 8 },
  { iso: 'DK', name: 'Dinamarca', dialCode: '45', flag: '🇩🇰', nationalMax: 8 },
  { iso: 'EG', name: 'Egito', dialCode: '20', flag: '🇪🇬', nationalMax: 10 },
  { iso: 'AE', name: 'Emirados Árabes', dialCode: '971', flag: '🇦🇪', nationalMax: 9 },
  { iso: 'EC', name: 'Equador', dialCode: '593', flag: '🇪🇨', nationalMax: 9 },
  { iso: 'SK', name: 'Eslováquia', dialCode: '421', flag: '🇸🇰', nationalMax: 9 },
  { iso: 'SI', name: 'Eslovênia', dialCode: '386', flag: '🇸🇮', nationalMax: 8 },
  { iso: 'ES', name: 'Espanha', dialCode: '34', flag: '🇪🇸', nationalMax: 9 },
  { iso: 'US', name: 'Estados Unidos', dialCode: '1', flag: '🇺🇸', nationalMax: 10 },
  { iso: 'EE', name: 'Estônia', dialCode: '372', flag: '🇪🇪', nationalMax: 8 },
  { iso: 'ET', name: 'Etiópia', dialCode: '251', flag: '🇪🇹', nationalMax: 9 },
  { iso: 'PH', name: 'Filipinas', dialCode: '63', flag: '🇵🇭', nationalMax: 10 },
  { iso: 'FI', name: 'Finlândia', dialCode: '358', flag: '🇫🇮', nationalMax: 10 },
  { iso: 'FR', name: 'França', dialCode: '33', flag: '🇫🇷', nationalMax: 9 },
  { iso: 'GA', name: 'Gabão', dialCode: '241', flag: '🇬🇦', nationalMax: 7 },
  { iso: 'GH', name: 'Gana', dialCode: '233', flag: '🇬🇭', nationalMax: 9 },
  { iso: 'GE', name: 'Geórgia', dialCode: '995', flag: '🇬🇪', nationalMax: 9 },
  { iso: 'GI', name: 'Gibraltar', dialCode: '350', flag: '🇬🇮', nationalMax: 8 },
  { iso: 'GR', name: 'Grécia', dialCode: '30', flag: '🇬🇷', nationalMax: 10 },
  { iso: 'GT', name: 'Guatemala', dialCode: '502', flag: '🇬🇹', nationalMax: 8 },
  { iso: 'GY', name: 'Guiana', dialCode: '592', flag: '🇬🇾', nationalMax: 7 },
  { iso: 'GF', name: 'Guiana Francesa', dialCode: '594', flag: '🇬🇫', nationalMax: 9 },
  { iso: 'GN', name: 'Guiné', dialCode: '224', flag: '🇬🇳', nationalMax: 9 },
  { iso: 'GW', name: 'Guiné-Bissau', dialCode: '245', flag: '🇬🇼', nationalMax: 7 },
  { iso: 'GQ', name: 'Guiné Equatorial', dialCode: '240', flag: '🇬🇶', nationalMax: 9 },
  { iso: 'HT', name: 'Haiti', dialCode: '509', flag: '🇭🇹', nationalMax: 8 },
  { iso: 'HN', name: 'Honduras', dialCode: '504', flag: '🇭🇳', nationalMax: 8 },
  { iso: 'HK', name: 'Hong Kong', dialCode: '852', flag: '🇭🇰', nationalMax: 8 },
  { iso: 'HU', name: 'Hungria', dialCode: '36', flag: '🇭🇺', nationalMax: 9 },
  { iso: 'YE', name: 'Iêmen', dialCode: '967', flag: '🇾🇪', nationalMax: 9 },
  { iso: 'IN', name: 'Índia', dialCode: '91', flag: '🇮🇳', nationalMax: 10 },
  { iso: 'ID', name: 'Indonésia', dialCode: '62', flag: '🇮🇩', nationalMax: 11 },
  { iso: 'IQ', name: 'Iraque', dialCode: '964', flag: '🇮🇶', nationalMax: 10 },
  { iso: 'IE', name: 'Irlanda', dialCode: '353', flag: '🇮🇪', nationalMax: 9 },
  { iso: 'IS', name: 'Islândia', dialCode: '354', flag: '🇮🇸', nationalMax: 7 },
  { iso: 'IL', name: 'Israel', dialCode: '972', flag: '🇮🇱', nationalMax: 9 },
  { iso: 'IT', name: 'Itália', dialCode: '39', flag: '🇮🇹', nationalMax: 10 },
  { iso: 'JM', name: 'Jamaica', dialCode: '1876', flag: '🇯🇲', nationalMax: 7 },
  { iso: 'JP', name: 'Japão', dialCode: '81', flag: '🇯🇵', nationalMax: 10 },
  { iso: 'JO', name: 'Jordânia', dialCode: '962', flag: '🇯🇴', nationalMax: 9 },
  { iso: 'KW', name: 'Kuwait', dialCode: '965', flag: '🇰🇼', nationalMax: 8 },
  { iso: 'LA', name: 'Laos', dialCode: '856', flag: '🇱🇦', nationalMax: 9 },
  { iso: 'LS', name: 'Lesoto', dialCode: '266', flag: '🇱🇸', nationalMax: 8 },
  { iso: 'LV', name: 'Letônia', dialCode: '371', flag: '🇱🇻', nationalMax: 8 },
  { iso: 'LB', name: 'Líbano', dialCode: '961', flag: '🇱🇧', nationalMax: 8 },
  { iso: 'LR', name: 'Libéria', dialCode: '231', flag: '🇱🇷', nationalMax: 8 },
  { iso: 'LY', name: 'Líbia', dialCode: '218', flag: '🇱🇾', nationalMax: 9 },
  { iso: 'LI', name: 'Liechtenstein', dialCode: '423', flag: '🇱🇮', nationalMax: 7 },
  { iso: 'LT', name: 'Lituânia', dialCode: '370', flag: '🇱🇹', nationalMax: 8 },
  { iso: 'LU', name: 'Luxemburgo', dialCode: '352', flag: '🇱🇺', nationalMax: 9 },
  { iso: 'MO', name: 'Macau', dialCode: '853', flag: '🇲🇴', nationalMax: 8 },
  { iso: 'MK', name: 'Macedônia do Norte', dialCode: '389', flag: '🇲🇰', nationalMax: 8 },
  { iso: 'MG', name: 'Madagascar', dialCode: '261', flag: '🇲🇬', nationalMax: 9 },
  { iso: 'MY', name: 'Malásia', dialCode: '60', flag: '🇲🇾', nationalMax: 10 },
  { iso: 'MW', name: 'Malawi', dialCode: '265', flag: '🇲🇼', nationalMax: 9 },
  { iso: 'MV', name: 'Maldivas', dialCode: '960', flag: '🇲🇻', nationalMax: 7 },
  { iso: 'MT', name: 'Malta', dialCode: '356', flag: '🇲🇹', nationalMax: 8 },
  { iso: 'MA', name: 'Marrocos', dialCode: '212', flag: '🇲🇦', nationalMax: 9 },
  { iso: 'MU', name: 'Maurício', dialCode: '230', flag: '🇲🇺', nationalMax: 8 },
  { iso: 'MX', name: 'México', dialCode: '52', flag: '🇲🇽', nationalMax: 10 },
  { iso: 'MZ', name: 'Moçambique', dialCode: '258', flag: '🇲🇿', nationalMax: 9 },
  { iso: 'MD', name: 'Moldávia', dialCode: '373', flag: '🇲🇩', nationalMax: 8 },
  { iso: 'MC', name: 'Mônaco', dialCode: '377', flag: '🇲🇨', nationalMax: 8 },
  { iso: 'MN', name: 'Mongólia', dialCode: '976', flag: '🇲🇳', nationalMax: 8 },
  { iso: 'ME', name: 'Montenegro', dialCode: '382', flag: '🇲🇪', nationalMax: 8 },
  { iso: 'NA', name: 'Namíbia', dialCode: '264', flag: '🇳🇦', nationalMax: 9 },
  { iso: 'NP', name: 'Nepal', dialCode: '977', flag: '🇳🇵', nationalMax: 10 },
  { iso: 'NI', name: 'Nicarágua', dialCode: '505', flag: '🇳🇮', nationalMax: 8 },
  { iso: 'NE', name: 'Níger', dialCode: '227', flag: '🇳🇪', nationalMax: 8 },
  { iso: 'NG', name: 'Nigéria', dialCode: '234', flag: '🇳🇬', nationalMax: 10 },
  { iso: 'NO', name: 'Noruega', dialCode: '47', flag: '🇳🇴', nationalMax: 8 },
  { iso: 'NZ', name: 'Nova Zelândia', dialCode: '64', flag: '🇳🇿', nationalMax: 9 },
  { iso: 'OM', name: 'Omã', dialCode: '968', flag: '🇴🇲', nationalMax: 8 },
  { iso: 'NL', name: 'Países Baixos', dialCode: '31', flag: '🇳🇱', nationalMax: 9 },
  { iso: 'PA', name: 'Panamá', dialCode: '507', flag: '🇵🇦', nationalMax: 8 },
  { iso: 'PG', name: 'Papua-Nova Guiné', dialCode: '675', flag: '🇵🇬', nationalMax: 8 },
  { iso: 'PK', name: 'Paquistão', dialCode: '92', flag: '🇵🇰', nationalMax: 10 },
  { iso: 'PY', name: 'Paraguai', dialCode: '595', flag: '🇵🇾', nationalMax: 9 },
  { iso: 'PE', name: 'Peru', dialCode: '51', flag: '🇵🇪', nationalMax: 9 },
  { iso: 'PL', name: 'Polônia', dialCode: '48', flag: '🇵🇱', nationalMax: 9 },
  { iso: 'PR', name: 'Porto Rico', dialCode: '1787', flag: '🇵🇷', nationalMax: 7 },
  { iso: 'PT', name: 'Portugal', dialCode: '351', flag: '🇵🇹', nationalMax: 9 },
  { iso: 'KE', name: 'Quênia', dialCode: '254', flag: '🇰🇪', nationalMax: 9 },
  { iso: 'GB', name: 'Reino Unido', dialCode: '44', flag: '🇬🇧', nationalMax: 10 },
  { iso: 'CF', name: 'República Centro-Africana', dialCode: '236', flag: '🇨🇫', nationalMax: 8 },
  { iso: 'CZ', name: 'República Tcheca', dialCode: '420', flag: '🇨🇿', nationalMax: 9 },
  { iso: 'DO', name: 'República Dominicana', dialCode: '1809', flag: '🇩🇴', nationalMax: 7 },
  { iso: 'RO', name: 'Romênia', dialCode: '40', flag: '🇷🇴', nationalMax: 9 },
  { iso: 'RW', name: 'Ruanda', dialCode: '250', flag: '🇷🇼', nationalMax: 9 },
  { iso: 'RU', name: 'Rússia', dialCode: '7', flag: '🇷🇺', nationalMax: 10 },
  { iso: 'SV', name: 'El Salvador', dialCode: '503', flag: '🇸🇻', nationalMax: 8 },
  { iso: 'SN', name: 'Senegal', dialCode: '221', flag: '🇸🇳', nationalMax: 9 },
  { iso: 'RS', name: 'Sérvia', dialCode: '381', flag: '🇷🇸', nationalMax: 9 },
  { iso: 'SG', name: 'Singapura', dialCode: '65', flag: '🇸🇬', nationalMax: 8 },
  { iso: 'SY', name: 'Síria', dialCode: '963', flag: '🇸🇾', nationalMax: 9 },
  { iso: 'SO', name: 'Somália', dialCode: '252', flag: '🇸🇴', nationalMax: 8 },
  { iso: 'LK', name: 'Sri Lanka', dialCode: '94', flag: '🇱🇰', nationalMax: 9 },
  { iso: 'SE', name: 'Suécia', dialCode: '46', flag: '🇸🇪', nationalMax: 9 },
  { iso: 'CH', name: 'Suíça', dialCode: '41', flag: '🇨🇭', nationalMax: 9 },
  { iso: 'SR', name: 'Suriname', dialCode: '597', flag: '🇸🇷', nationalMax: 7 },
  { iso: 'TH', name: 'Tailândia', dialCode: '66', flag: '🇹🇭', nationalMax: 9 },
  { iso: 'TW', name: 'Taiwan', dialCode: '886', flag: '🇹🇼', nationalMax: 9 },
  { iso: 'TZ', name: 'Tanzânia', dialCode: '255', flag: '🇹🇿', nationalMax: 9 },
  { iso: 'TL', name: 'Timor-Leste', dialCode: '670', flag: '🇹🇱', nationalMax: 8 },
  { iso: 'TG', name: 'Togo', dialCode: '228', flag: '🇹🇬', nationalMax: 8 },
  { iso: 'TT', name: 'Trinidad e Tobago', dialCode: '1868', flag: '🇹🇹', nationalMax: 7 },
  { iso: 'TN', name: 'Tunísia', dialCode: '216', flag: '🇹🇳', nationalMax: 8 },
  { iso: 'TR', name: 'Turquia', dialCode: '90', flag: '🇹🇷', nationalMax: 10 },
  { iso: 'UA', name: 'Ucrânia', dialCode: '380', flag: '🇺🇦', nationalMax: 9 },
  { iso: 'UG', name: 'Uganda', dialCode: '256', flag: '🇺🇬', nationalMax: 9 },
  { iso: 'UY', name: 'Uruguai', dialCode: '598', flag: '🇺🇾', nationalMax: 8 },
  { iso: 'UZ', name: 'Uzbequistão', dialCode: '998', flag: '🇺🇿', nationalMax: 9 },
  { iso: 'VE', name: 'Venezuela', dialCode: '58', flag: '🇻🇪', nationalMax: 10 },
  { iso: 'VN', name: 'Vietnã', dialCode: '84', flag: '🇻🇳', nationalMax: 10 },
  { iso: 'ZM', name: 'Zâmbia', dialCode: '260', flag: '🇿🇲', nationalMax: 9 },
  { iso: 'ZW', name: 'Zimbábue', dialCode: '263', flag: '🇿🇼', nationalMax: 9 },
];

export const DEFAULT_PHONE_COUNTRY =
  PHONE_COUNTRIES.find((country) => country.iso === 'BR') ?? PHONE_COUNTRIES[0];

export function findPhoneCountry(iso: string): PhoneCountry {
  return (
    PHONE_COUNTRIES.find((country) => country.iso === iso) ?? DEFAULT_PHONE_COUNTRY
  );
}
